export const ADD_MARKER_MUTATION = "ADD_MARKER_MUTATION";
export const REMOVE_MARKER_MUTATION = "REMOVE_MARKER_MUTATION";
export const TOGGLE_READONLY_MUTATION = "TOGGLE_READONLY_MUTATION";
export const ADD_ERROR_MUTATION = "ADD_ERROR_MUTATION";
export const CLEAR_ERRORLIST_MUTATION = "CLEAR_ERRORLIST_MUTATION";
export const REMOVE_ERROR_MUTATION = "REMOVE_ERROR_MUTATION";
export const SET_MARKER_LIST_MUTATION = "SET_MARKER_LIST_MUTATION";
export const SET_LANGUAGE_MUTATION = "SET_LANGUAGE_MUTATION";
